.github/workflows/testing.yml
This will run the unittests for pull requests against `master` and `next` branches.
=> GitHub workflow for running tests

.github/workflows/testing.yml, .gitignore, .pre-commit-config.yaml, README.rst, ibeis/__init__.py, ibeis/algo/hots/neighbor_index.py, ibeis/tests/run_tests.py, ibeis/web/apis_engine.py, ibeis/web/apis_query.py, ibeis/web/test_api.py, setup.cfg
This merges the changes from the next branch into master.
=> Merging changes from next branch into master

ibeis/core_annots.py, ibeis/web/routes_ajax.py
Just a few renaming of imports that were missed.
=> Fix NameError associated with *tool to *tool_ibeis changes

ibeis/dtool/_grave_depcache.py, ibeis/dtool/base.py, ibeis/dtool/depcache_control.py, ibeis/dtool/depcache_table.py, ibeis/dtool/example_depcache.py, ibeis/dtool/example_depcache2.py, ibeis/dtool/input_helpers.py, ibeis/dtool/old_stuff.py, ibeis/guitool/PrefWidget2.py, ibeis/guitool/PreferenceWidget.py, ibeis/guitool/__init__.py, ibeis/guitool/api_thumb_delegate.py, ibeis/guitool/guitool_components.py, ibeis/guitool/guitool_dialogs.py, ibeis/guitool/mpl_embed.py, ibeis/guitool/mpl_widget.py
```
tool=plottool; grep -rl ${tool}_ibeis ./ibeis | xargs sed -i \
-e "s/from ${tool}_ibeis/from ibeis.$tool/g" \
-e "s/import ${tool}_ibeis/import ibeis.$tool/g" \
-e "s/${tool}_ibeis/$tool/g" \
-e "s/-m $tool/-m ibeis.$tool/g"
```
=> Rename plottool aka plottool_ibeis import references

devops/provision/Dockerfile
We are trying to get rid of the "next" branch and use "master" instead.
Some repos don't have the "next" branch anymore so change the branches
to master:
- flann
- hesaff
- ubelt
- vtool
=> Fix provision Dockerfile to use master for some repos

ibeis/detecttools/pascaldata/pascal_image.py, ibeis/dtool/_grave_depcache.py, ibeis/unstable/_scriptvsone_grave.py, ibeis/web/apis_microsoft.py
This contains a set of changes that fix various SyntaxErrors in a few modules. See the commit description for details.
I ran over these while attempting to run a dependency scanning tool.
My guess is that the modules these changes touch are no longer actively used within the codebase. Otherwise we'd have hit them sooner when starting the application. I'll make a mental note to come back to these at some point, because this is technical debt that should be easy to pay off.
=> Fixing SyntaxErrors in Python 3

devops/Dockerfile, devops/provision/Dockerfile
* Update location of runtime script for the container's entry-point invocation
* Update container base name for the install stage
* Remove what appears to be a redundant pull of code that would have been pulled in the prior build step
* Remove all `.git` directories with a single command
* Update repository branches and directory names
The commits are fairly atomic. I'd suggest a rebase merge.
=> Further fixes for the container build

.pre-commit-config.yaml, dev/_scripts/CMakeLists.txt, setup.cfg, wbia/algo/hots/chip_match.py, wbia/control/manual_annot_funcs.py, wbia/control/manual_image_funcs.py, wbia/control/manual_review_funcs.py, wbia/dbio/ingest_mdb.py, wbia/dev.py, wbia/expt/experiment_drawing.py, wbia/expt/test_result.py, wbia/gui/guiback.py, wbia/guitool/CMakeLists.txt, wbia/other/dbinfo.py, wbia/other/ibsfuncs.py, wbia/plottool/abstract_interaction.py, wbia/plottool/draw_func2.py, wbia/scripts/classify_shark.py, wbia/scripts/postdoc.py, wbia/scripts/thesis.py, wbia/unstable/demobayes.py, wbia/unstable/iccv.py, wbia/web/routes_submit.py
- Add brunette pre-commit hook for codestyle correction
- Run brunette on all files
- Add cmake format pre-commit hook
- Run cmake format pre-commit hook
=> Add and run pre-commit hooks

.gitignore, setup.py, wbia/__init__.py
This pulls the version information from git. It also writes the
version to file for non-git distribution of the code (e.g. wheel).
=> Use setuptools_scm for version discovery through git

pyproject.toml, requirements.txt, requirements/build.txt, setup.py
- Add requirements/build.txt
- Add build requirements to pyproject.toml
=> Update build requirements

devops/provision/Dockerfile
Fix the install instruction for pydarknet
=> Fix pydarknet install instruction

wbia/control/IBEISControl.py, wbia/expt/experiment_helpers.py, wbia/templates/notebook_cells.py
We renamed the plugin to wbia_flukematch recently.
=> Rename ibeis_flukematch references to wbia_flukematch

.github/workflows/testing.yml
This provides us with a quick but thorough workflow for running the
tests against any pushed changes.
We aren't testing against all versions of python, but instead only
against our deployment version. This is intentional, as our deployment
is the critical focus for now. Later adjustments can be made to do a
full matrix build if necessary. More than likely matrix testing would
be on pull request creation. This tries to simply get us to a place
where the tests are routinely running.
Hopefully this will lead us to a bright future of green checkmarks ✅.
=> Revised and quickened CI testing workflow

wbia/demodata.py, wbia/tests/helpers.py, wbia/tests/reset_testdbs.py
See each commit and the message body for each commit. These are just a few small fixes.
=> Clean up reset dbs module

wbia/algo/graph/mixin_matching.py, wbia/algo/graph/mixin_viz.py, wbia/algo/graph/mixin_wbia.py, wbia/algo/hots/neighbor_index.py, wbia/algo/hots/nn_weights.py, wbia/algo/verif/deploy.py, wbia/algo/verif/pairfeat.py, wbia/algo/verif/vsone.py, wbia/control/manual_featweight_funcs.py, wbia/viz/viz_chip.py, wbia/web/graph_server.py
(see commit messages for details)
Closes #51
=> Fix tests on github workflow

.github/workflows/nightly.yml
Use the latest code for building the docker images.
=> Use the develop branch in github nightly workflow

wbia/control/docker_control.py
Since docker 4.3.1 (the python package), `docker.from_env()` tries to
connect to docker and throws an error if it's not available.  Since
deepsense is a plugin and should be optional, we shouldn't be throwing
an error here.
---
This should fix the nightly build :crossed_fingers:
=> Stop creating docker client on import in control/docker_control.py

.dockerfiles/docker-compose.env, .dockerfiles/docker-entrypoint.sh, Dockerfile, docker-compose.yml, requirements.txt, requirements/postgres.txt, setup.cfg, setup.py, wbia/conftest.py, wbia/control/DB_SCHEMA.py, wbia/control/IBEISControl.py, wbia/control/_sql_helpers.py, wbia/dtool/depcache_control.py, wbia/dtool/sql_control.py
This is a bit over everything... probably best to look through each commit to get a better sense of the changes.
The gist is towards moving to the URI based connection, using the runtime container for development and setting foundational elements for postgres integration.
---
Tests are failing unrelated to these changes
=> URI and development changes

devops/Dockerfile, wbia/control/manual_annot_funcs.py, wbia/control/manual_image_funcs.py, wbia/core_annots.py, wbia/core_images.py, wbia/other/ibsfuncs.py, wbia/web/graph_server.py
@bluemellophone can you submit a PR for changes in the future? That will give the CI a chance to tell you if it caught any issues prior to merge. It would also be beneficial to have us look over your changes as both a learning experience and to double check for simple mistakes.
The small set of changes in this PR attempt to fix some low hanging fruit failures.
The GraphClient has a test in it that is still failing. This looks to be due to the changes around replacing future_utils (aka future_actors). AFAICT the future isn't getting returned, but I didn't look into it further than that. @bluemellophone can you please look into the failure?
=> Attempt to fix broken tests on tip of 'develop'

wbia/dtool/depcache_table.py
This constant is set to True. Yet for an unknown reason the code
checks it as if it would change or not be True. And if it weren't True
we'd see AssertionErrors being raised, which wouldn't be the desired effect.
=> Remove STORE_CFGDICT

.github/workflows/testing.yml, requirements/runtime.txt, wbia/algo/graph/mixin_loops.py
Also remove test job name in testing workflow
This should show the python version and OS when we look at a github job
run.
"test (ubuntu-latest, 3.6)"
=> Add python versions to 3.7, 3.8 in testing workflow

wbia/control/IBEISControl.py, wbia/dtool/depcache_control.py, wbia/dtool/depcache_table.py
Just switching the first argument of class methods to 'self'.
=> Use the 'self' class argument convention

requirements/runtime.txt
=> Use wbia-lightnet from pypi

requirements/runtime.txt, wbia/constants.py, wbia/control/manual_wildbook_funcs.py, wbia/dev.py, wbia/other/ibsfuncs.py, wbia/params.py, wbia/web/apis_engine.py, wbia/web/apis_sync.py
This PR cherry picks changes added to `develop` that are not related to SQLAlchemy, which is showing severe slowdowns on production environments.  We will keep the develop branch ini its current state (no rollback) but before any updates to the database controller is merged into master, the performance issues need to be resolved.
=> Hotfixes for Master to segment changes from SQLAlchemy

devops/Dockerfile, devops/dependencies/Dockerfile, devops/provision/Dockerfile, wbia/dev.py
See the individual commits for details.
=> Minor adjustments to improve usage of the wildme/wbia* images

.gitignore, requirements/runtime.txt, setup.py, wbia/cli/convert_hsdb.py, wbia/cli/testdbs.py, wbia/control/DB_SCHEMA.py, wbia/control/IBEISControl.py, wbia/control/_sql_helpers.py, wbia/control/manual_annot_funcs.py, wbia/control/manual_gsgrelate_funcs.py, wbia/control/manual_image_funcs.py, wbia/control/manual_imageset_funcs.py, wbia/control/manual_lblannot_funcs.py, wbia/control/manual_lblimage_funcs.py, wbia/control/manual_meta_funcs.py, wbia/control/manual_part_funcs.py, wbia/control/manual_review_funcs.py, wbia/dtool/depcache_control.py, wbia/dtool/depcache_table.py, wbia/dtool/example_depcache.py, wbia/dtool/example_depcache2.py, wbia/dtool/sql_control.py, wbia/dtool/types.py, wbia/entry_points.py, wbia/gui/guiback.py, wbia/init/filter_annots.py, wbia/other/ibsfuncs.py, wbia/tests/dtool/test_sql_control.py, wbia/web/routes.py
These results are generated using [this benchmarking script](https://gist.github.com/karenc/e20bdcbc14d12ac06017987f96a2d846) on cthulhu using the flukebook dataset:
urls                                     | develop     | optimized-queries
------------------------------------------|-------------|----------      
/api/annot/                               | 4s          | 5s             
/view/                                    | 8s          | 13s            
/view/imagesets/                          | 24s         | 34s            
/api/image/                               | 1s          | 1s             
/api/name/                                | 0s          | 0s             
/api/review/                              | 0s          | 0s             
/turk/ …
=> Use SQLAlchemy

devops/Dockerfile, devops/provision/Dockerfile, wbia/control/IBEISControl.py, wbia/core_annots.py, wbia/entry_points.py, wbia/other/ibsfuncs.py, wbia/web/apis.py, wbia/web/apis_sync.py
Add build support for https://github.com/WildbookOrg/wbia-plugin-orientation.
=> Add Orientation Plug-in by Olga Moskvyak

requirements/runtime.txt, wbia/algo/verif/sklearn_utils.py
The upgrade from scikit-learn 0.24.2 to 1.0 changed the arguments so we need to
use keyword arguments instead:
```
File "/home/runner/work/wildbook-ia/wildbook-ia/wbia/web/graph_server.py", line 185, in handle
return func(**message)
File "/home/runner/work/wildbook-ia/wildbook-ia/wbia/web/graph_server.py", line 569, in resume
user_request = actor.infr.resume()
File "/home/runner/work/wildbook-ia/wildbook-ia/wbia/algo/graph/mixin_loops.py", line 642, in resume
user_request = next(infr._gen)
File "/home/runner/work/wildbook-ia/wildbook-ia/wbia/algo/graph/mixin_loops.py", line 95, in main_gen
yield from infr.hardcase_review_gen()
File "/home/runner/work/wildbook-ia/wildbook-ia/wbia/algo/graph/mixin_loops.py", line 174, in hardcase_review_gen
verifiers = …
```
=> Fix StratifiedGroupKFold __init__ TypeError

docs/_sources/index.rst.txt, docs/index.html
Minor edits:
* A few Oxford commas (seems to be the accepted style in this docset)
* which / for which grammar
* Used a list for algorithms, which scans better in documentation
=> Docs index edit

devops/Dockerfile, devops/install.ubuntu.sh, devops/provision/Dockerfile, wbia/control/IBEISControl.py
Adds plugin to Dockerfiles and IBEIScontrol
=> Add blend plugin

wbia/algo/detect/densenet.py, wbia/algo/detect/lightnet.py
Adding the configurations for the leopard shark models.
- Adding the detector models and labeled model in the configuration
=> Leopard shark dev

.github/workflows/docker-publish-arm64.yaml, requirements/build.txt, requirements/postgres.txt, requirements/runtime.txt
This fix includes the following
1. Docker write error that prevents the daily docker nightly build
2. Version fixes for all runtime pip packages.
=> Docker write error patch & pip runtime version fixes

.github/workflows/docker-publish.yaml, requirements/problematic.txt, requirements/tests.txt, scripts/ci_prepare_linux_for_build.sh
Fix the missing pip versions update, 
docker build scripts and
image build
=> Docker write error patch v2

requirements/runtime.txt
The additional cuda packages removed
=> The additional cuda packages removed

devops/Dockerfile
Allows for using the --pie flag for containers.
=> reenables pie v1 setup for docker build

requirements/runtime.txt
included main branch of vtool installed
=> Update runtime.txt to include vtool

wbia/algo/detect/efficientnet.py, wbia/core_annots.py
Adds a new efficientnet labeler with model weights for sea turtles. 
To configure the labeler for the detection (/api/engine/detect/cnn/lightnet/), use the field `"labeler_algo": "efficientnet"`.
=> Adds efficientnet labeler

.github/workflows/docker-publish.yaml, devops/Dockerfile, devops/_config/deprecated.sh, devops/develop/Dockerfile, devops/install.ubuntu.sh, devops/migrate.sh, devops/provision/Dockerfile, requirements/runtime.txt, run_developer_setup.sh, wbia/__main__.py
- Smoketest is added back after Imgur URLs are replaced,
- no-cache-dir is added to all PIP installs
- Free disk space is added to build
=> Replace imgur urls

wbia/algo/detect/densenet.py, wbia/algo/detect/lightnet.py
=> snal_configs

devops/base/Dockerfile
Update the version cuda-11.7.1-nvidia
=> Update Dockerfile cuda-11.7.1-nvidia

wbia/algo/detect/densenet.py, wbia/algo/detect/efficientnet.py, wbia/algo/detect/lightnet.py
=> Deer Detection

.github/workflows/testing.yml, requirements/runtime.txt, wbia/algo/graph/mixin_simulation.py, wbia/dtool/copy_sqlite_to_postgres.py, wbia/gui/newgui.py
=> testing-fluke8-fix

.github/workflows/docker-publish.yaml
=> docker build branch fix

wbia/algo/detect/lightnet.py
Included trout v1 version of localizer 
Notes: https://www.notion.so/Trout-Detection-6af7f6d45d8b4bd4ad51bf47bfaf1c06?pvs=4#1df5ba8682f944309a1e1d3c5985acb2
=> trout v1 localizer update

README.rst
removed non-functional pypi instructions, updated to working instructions based on recent testing, removed duplicate documentation reference, added disclaimer about support limitations
=> updated support instructions and limits

wbia/algo/detect/efficientnet.py, wbia/algo/detect/lightnet.py
Update Shark lighnet models
https://www.notion.so/Deplyment-Configuration-2f8ce3ca57044ff084339357983d7fcf
=> Update Shark lighnet models

devops/Dockerfile
Remove finFindr CurvRank algorithms
=> Remove finFindr CurvRank algorithms

wbia/algo/detect/efficientnet.py, wbia/algo/detect/lightnet.py
Adding Grouper Detector, labeler and Orientation Models.
Training & Test Results are found here :  https://www.notion.so/Multi-Grouper-Detection-Orientation-and-Labeler-v2-70086337fcb5432e96977f3a8dbea9e0
=> Grouper Detector

wbia/algo/detect/efficientnet.py, wbia/algo/detect/lightnet.py
Detector and Efficientnet labeler is added to Whaleshark
=> whaleshark detector and effnet labeler is added
